# Generated by Django 5.1.3 on 2024-12-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatistics',
            old_name='successful_analyses',
            new_name='successful_image_analyses',
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='successful_text_analyses',
            field=models.IntegerField(default=0),
        ),
    ]
